### ISSUE TITLE
Berkshire missing from list of UK counties

### ISSUE THREAD

**Issue by ancastoica** [country-regions/country-region-data#105]
Hey,

Our UK product managers have raised that [Berkshire](https://en.wikipedia.org/wiki/Berkshire) seems to be missing from the list of UK regions, would it be possible to add it ?

Thanks!

PS: thanks a lot for this very useful library :)

**Comment by benkeen** [comment]
Thanks! Will update.

**Comment by benkeen** [comment]
Thanks! This was fixed a while back, closing.
