### ISSUE TITLE
Cayman Islands listing cities and not states/regions

### ISSUE THREAD

**Issue by sbarter510** [country-regions/country-region-data#109]
Currently Cayman Islands is listing Creek, Eastern, Midland, South Town, Spot Bay, Stake Bay, West End, and Western. The states of Cayman Islands should include Grand Cayman, Little Cayman and Cayman Brac (perhaps some others that I am not aware of)

**Comment by benkeen** [comment]
Thansk @sbarter510, this'll be in today's 3.0.0 release.
