### ISSUE TITLE
List of Cities in the Philippines - Wiki

### ISSUE THREAD

**Issue by cauldyclark15** [country-regions/country-region-data#12]
Hi!

As per request I will attach a wikipedia link of all cities in the Philippines. Kindly update the repo. Thank you very much.

https://en.wikipedia.org/wiki/List_of_cities_in_the_Philippines

**Comment by benkeen** [comment]
Ah! Sorry for the confusion - we actually a need a list of _regions_ for the country, not cities. Here's the current list: https://github.com/benkeen/country-region-data/blob/master/data.json#L11748-L12068

**Comment by pukaslim** [comment]
I cannot find Manila or Metro Manila in the Philippines' region list but I find the list is same as provinces in the Philippines. I refer the data from the below wikipedia link.
https://en.wikipedia.org/wiki/Provinces_of_the_Philippines

**Comment by leschaller1** [comment]
+1 to adding a Metro Manila option. Getting many requests from people living in the Philippines for an MNL short code option in our dropdown (Looks like ISO code is PH-00 though, not sure if you'd prefer that). It is at the end of this list https://en.wikipedia.org/wiki/Provinces_of_the_Philippines#List_of_provinces. Considering 12.8% of the population is in this region, I think it would be a good addition. I can open up a PR if you agree @benkeen

**Comment by benkeen** [comment]
That sounds pretty reasonable, sure. If you wouldn't mind adding a PR that'd be great @leschaller1.
