### ISSUE TITLE
Hungary region missing

### ISSUE THREAD

**Issue by supermastermind** [country-regions/country-region-data#133]
Hi,
You may consider completing the Hungary region list with: 
  {\
    "name": "Jász-Nagykun-Szolnok",\
    "sc": "JN"\
  },\
as this region exists in Hungary, as described in wikipedia page: [https://en.wikipedia.org/wiki/Counties_of_Hungary](url)
Thanks & BR

**Comment by benkeen** [comment]
Thanks for this, just going through a few updates + I'll release 2.8.0 today with them. 

I do see this region in the list now though, but it's set to "N" not "JN" for the shortcode. I'll fix it.
