### ISSUE TITLE
Missing region for Romania - Bucuresti

### ISSUE THREAD

**Issue by ElenaIf** [country-regions/country-region-data#134]
Hi!

One of Romanian regions is missing - [Regiunea București](https://en.wikipedia.org/wiki/Regiunea_Bucure%C8%99ti) 

Here is Wikipedia page: https://en.wikipedia.org/wiki/Regions_of_the_People%27s_Republic_of_Romania 

I think it is also related to this pull request - https://github.com/country-regions/country-region-data/pull/127 

Thank you!

**Comment by benkeen** [comment]
Thanks @ElenaIf - I added a comment to the PR but if it's not update in the next few days I'll update it and get a new version out. Ping me if you don't see a new version in the next week.

**Comment by ElenaIf** [comment]
The region was added, thanks!
