### ISSUE TITLE
Incorrect module format

### ISSUE THREAD

**Issue by Akiyamka** [country-regions/country-region-data#139]
Can't use this package with `VITE v4.2.1`. Build crashes with next message:
```
country-region-data doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

```

**Comment by benkeen** [comment]
Thanks @Akiyamka. Hmm, ok from my understanding this error is technically correct. The "main" entry points to `dist/data.js` - that contains the exports in es6 `export` syntax. "module" is the one that should point to that. 

Let me think on this. Changing it is fine, it'll just be a breaking change so it'll have to be a major version bump and I use it for country-region-selector and other plugins. I need to ensure they continue to work.

**Comment by quiquelhappy** [comment]
any workarounds?

**Comment by matt-narvar** [comment]
Just following up on this. Jest throws on this issue too:

```
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

...
```

```
SyntaxError: Unexpected token 'export'
```

**Comment by benkeen** [comment]
Hey guys, sorry for not getting to this. 

What I'll do is the following: 
- bump the major version to 3 + document it in the README. 
- The current es6 export will now be set to the "module" property in the package.json file
- Set the data-umd.js as the "main" entry point. 

That last one worries me a bit; UMD is ancient + while it should work, I fear it may cause peoples bundle sizes to skyrocket if their build tool pulls in that over the module format. Still, I think it's the way to go. Let's see what fallout we get...

Will release 3.0.0 shortly.
