### ISSUE TITLE
Extra spaces in names.

### ISSUE THREAD

**Issue by smialy** [country-regions/country-region-data#14]
There are some exta space. Is it required?

`{
    "name":"  Mişrātah",
    "shortCode":"MI"
}`
and
`{
    "name":"  Edineț",
    "shortCode":"ED"
}`

**Comment by benkeen** [comment]
No, not required. It was probably just automated when adding it. I'd rather the spaces not be there, but it's not a big deal - they are (or should be) trimmed out by the code.

**Comment by benkeen** [comment]
This doesn't appear to be an issue any more.
