### ISSUE TITLE
Cayman Islands not showing correct Regions

### ISSUE THREAD

**Issue by Jen-DG** [country-regions/country-region-data#142]
The Cayman Islands are showing incorrect regions. The regions should be: Bodden Town, East End, George Town, North Side and West Bay

Can this please be updated?

 Its currently showing: Creek, Eastern, Midland, South Town, Spot Bay, Stake Bay, West End, Western

**Comment by benkeen** [comment]
Hey @Jen-DG - sure, do you have a verified source for the correct regions + short codes? I can update the list.

**Comment by Jen-DG** [comment]
Hi Ben,

Thanks so much for your help.

As far as I can see from google.

Grand Cayman consists of five districts:

George Town - GT
Bodden Town - BT
West Bay - WB
North Side - NS
East End - EE

And then the two smaller Cayman Islands, Little Cayman and Cayman Brac,
form a sixth district:

Sister Islands - SI

I had a look at this site: https://www.okcayman.com/cayman-islands-districts

As well as wikipedia.

I also consulted chatGPT 😆

**Comment by benkeen** [comment]
Cool ok, I'll update it on Sunday. :)
