### ISSUE TITLE
Missing Regions in the Bahamas

### ISSUE THREAD

**Issue by bmcnamara16** [country-regions/country-region-data#154]
Per iso standards  in the bahamas,  could we please add the following regions for the bahamas https://www.iso.org/obp/ui/#iso:code:3166:BS

`      {
        "name": "Central Andros",
        "shortCode": "43"
      },
      {
        "name": "Central Eleuthera",
        "shortCode": "44"
      },
      {
        "name": "Grand Cay",
        "shortCode": "45"
      },
      {
        "name": "Hope Town",
        "shortCode": "46"
      },
      {
        "name": "Mangrove Cay",
        "shortCode": "47"
      },
      {
        "name": "Spanish Wells",
        "shortCode": "48"
      }`

@benkeen :)

**Comment by benkeen** [comment]
Thanks! Merged.
