### ISSUE TITLE
Can Kosovo be added to the list of countries?

### ISSUE THREAD

**Issue by suitedjimster** [country-regions/country-region-data#31]
https://www.britannica.com/place/Kosovo

**Comment by benkeen** [comment]
Yes, absolutely. Do you happen to know what's people use as regions within the country? Districts or municipalities?
https://en.wikipedia.org/wiki/Administrative_divisions_of_Kosovo

**Comment by suitedjimster** [comment]
I would simply put region name "Kosovo" for now. At least that will be an improvement
