### ISSUE TITLE
Missing region for Romania: Ilfov

### ISSUE THREAD

**Issue by alexgheorghiu** [country-regions/country-region-data#46]
It seems that, at least for Romania, a region is missing: [Ilfov](https://en.wikipedia.org/wiki/Ilfov_County).

**Comment by benkeen** [comment]
Hey @alexgheorghiu, is it Ilfov or Bucharest-Ilfov? 
https://en.wikipedia.org/wiki/Bucure%C8%99ti_-_Ilfov
https://en.wikipedia.org/wiki/Ilfov_County

Seems like from this page it's the former:
https://en.wikipedia.org/wiki/Counties_of_Romania
