### ISSUE TITLE
Uppsala, Sweden in country-region-data but not in selector

### ISSUE THREAD

**Issue by willkuhn** [country-regions/country-region-data#57]
Uppsala, Sweden is included in the country-region-data data.json, along with 20 other Swedish regions, but for some reason it doesn't appear in the [country-regions-selector](http://country-regions.github.io/country-region-selector/) under "Sweden" (the other 20 do).

Its syntax in data.json appears to be OK (pasted below). Why might this be?

```
            {
                "name": "Uppsala",
                "shortCode": "C"
            },
```

Thanks for providing this invaluable resource and cheers,
Will

**Comment by lauralouiset** [comment]
@willkuhn I suspect this is because the live demo uses an older version of this package, as Uppsala does indeed appear in the data.

**Comment by sm5por** [comment]
@lauralouiset I added Uppsala county along with [a few other edits to data.json on Sep 22, 2019](https://github.com/country-regions/country-region-data/commit/f83cab4cc34ba9178a0d3191192ae07bd058f4a2#diff-edba02854c29b21582400e7a9936e108). I don't know why it was missing earlier. I wasn't aware of the live demo (nor am I sure now whether I'm linking this comment to that edit in the most appropriate way; the Guidelines seem to be silent on that).

**Comment by lauralouiset** [comment]
oh sorry -- wasn't aware you had fixed this. I suggest you close this issue if it has been resolved.
