### ISSUE TITLE
🐎 Allow some country's regions to be included/excluded by tree shaking

### ISSUE THREAD

**Issue by BevanR** [country-regions/country-region-data#86]
A package that uses this package must include or exclude all data for all countries. For a web UI that only needs regions for some countries, this makes `country-region-data` an unnecessarily very large part of its bundle.

It would be nice if data could be imported by country, so that data for unused countries is not included in the bundled app.

E.g.

```js
import countriesOnly from 'country-region-data/countries'
import { us, ca } from 'country-region-data/regions'
```

or 

```js
import countriesOnly from 'country-region-data/countries'
import us from 'country-region-data/us'
import ca from 'country-region-data/ca'
```

**Comment by benkeen** [comment]
This is a great idea - much better than the existing manual process of manually generating a build with the subset of country/regions.

**Comment by benkeen** [comment]
I'll do this for the next release. Thanks!

**Comment by BevanR** [comment]
Wonderful. Thank you. Please let me know when you have something we can test.

**Comment by benkeen** [comment]
Hi @BevanR - all done. Try importing `2.0.0` of the script. It contains typings of the exported data. Let me know if you any problem with it!

**Comment by BevanR** [comment]
Thanks @benkeen!

`import { AU, CA, GB, US } from 'country-region-data'`  gets regions for the countries the project needs and (importantly) omits regions for countries it does not need from the build.

However if I also want a list of all country names and short-codes, I still need to either import `allCountries` (reverting the performance benefit) or rebuild the data structure from `countryNames` and `countryShortCodes`—and also trust that they are ordered correspondingly. (Are they?)

A single data structure with country data (excluding regions) would be nice. E.g.

```ts
[
  ['Afghanistan', 'AF'],
  ['Australia', 'AU'],
  // ...
]
```

But maybe this invalidates other optimisations you've made?

Alternatively, perhaps the tuples are more useful than flat `countryNames` and `countryShortCodes` arrays?

Certainly it is easier in JavaScript to flatten the two-dimensional array than merge two one-dimensional arrays. I.e.

```ts
// Get country names from country data.
const countryNames = countries.map(([, slug]) => slug)
```

vs

```ts
// Build pairs of names and slugs.
const countryPairs = countryShortCodes.map((slug, i) => ([countryNames[i], slug))
for (let i = 0; i < countryShortCodes.length; i++) {
  countryPairs.push([countryNames[i], countryShortCodes[i]])
}
```

Also, `import { AU, CA, GB, US } from 'country-region-data'`  builds fine with our Vue/webpack build tooling. However Jest chokes on it because it expects packages in `node_modules/` to be compiled already. I think this is Jest's or the NPM ecosystem's problem though, not country-data-region's problem. [This solution seems to work fine](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring).

**Comment by BevanR** [comment]
@benkeen Any thoughts on my last comment?

**Comment by benkeen** [comment]
Hey sorry, give me another day or two & will get back to you!

**Comment by benkeen** [comment]
Hey @BevanR, very sorry for the wait. The country array tuples sounds fine. Yeah I can see how that could be useful. 

This would increase the size of the UMD file, but to be honest I'm not too worried. Any modern application would be using the es6 file by now, so a little extra weight to the file is fine given that it's tree-shakeable. I should have time tomorrow to get a new version out containing this addition.
