### ISSUE TITLE
List of Cities in the Philippines

### ISSUE THREAD

**Issue by bilalrashid300** [country-regions/country-region-data#99]
Regions list is not valid.
![Capture](https://user-images.githubusercontent.com/60001564/138439839-b08298dc-6421-42fd-ba80-772217415a25.JPG)
ref: https://en.wikipedia.org/wiki/Provinces_of_the_Philippine
correct list: [phillippinesRegions.txt](https://github.com/country-regions/country-region-data/files/7396383/phillippinesRegions.txt)

**Comment by benkeen** [comment]
Thanks @bilalrashid300, I'll update it in todays release based on this data. Looks like someone had set the region values to cities, like you said. 
https://en.wikipedia.org/wiki/Regions_of_the_Philippines
